04-Model / Caching
LangChain-OpenTutorial/LangChain-OpenTutorial pull request #13
Opened 2024-12-29 15:07 UTC by XaviereKU

[Team] Existing content development teams 3
[Title] Caching
[Version] initial
[Language] ENG
[Package] langchain, langchain-openai

LangChain Caching tutorial

Implemented caching using globals.set_llm_cache, cache.InMemoryCache and cache.SQLiteCache.
Demonstrated InMemoryCache and SQLiteCache with OpenAI API calls and local LLM served with vLLM.

2024-12-29 17:11 UTC, teddylee777 requested changes
from langchain_community.cache import SQLiteCache
from langchain_core.globals import set_llm_cache

로 일괄 업데이트 하였습니다.
이전에 작성해 주신 import 구문은 legacy 가 될  가능성이 높아 최신 가이드에 맞춰 교정하였습니다.

2024-12-30 15:53 UTC, teddylee777 submitted a review, later dismissed
리뷰 완료 하였습니다.
양질의 튜토리얼을 만들어 주셔서 감사합니다.
동작 확인도 완료 하였습니다!

2024-12-31 09:30 UTC, obov approved these changes
[Review]
1. Review OS(Windows/Mac/Linux): Mac
2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO): YES
5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
6. 모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): 
7. 기타 의견: `cache` 기능사용시 참고해 바로 적용하기 좋은 글인 것 같습니다. 코멘트는 천천히 확인해주셔도 됩니다. 깔끔한 글인 것 같습니다. 고생하셨습니다. 👍

2024-12-31 09:30 UTC, obov commented on 04-MODEL/02-Cache.ipynb
> +        "        # \"vllm\", # this is for optional section\n",
`langchain-anthropic`, `langchain_text_splitters` 이거 두개 사용하시는지 확인 한번 부탁드립니다.

2024-12-31 09:31 UTC, obov commented on 04-MODEL/02-Cache.ipynb
> +        "    ```"
제가 직접 돌렸을 때 나온 터미널 로그입니다.

2024-12-31 19:01 UTC, XaviereKU commented on 04-MODEL/02-Cache.ipynb
> +        "        # \"vllm\", # this is for optional section\n",
vllm이 linux를 사용해야해서 mac os native로는 설치가 안되고, 도커로 올려서 설치해보려했는데 계속 fail 상태입니다.
추후 방법을 찾게되면 다음 파일 작업시에라도 추가하도록 하겠습니다.

2024-12-31 19:01 UTC, XaviereKU commented on 04-MODEL/02-Cache.ipynb
> +        "    ```"
vllm이 linux를 사용해야해서 mac os native로는 설치가 안되고, 도커로 올려서 설치해보려했는데 계속 fail 상태입니다.
추후 방법을 찾게되면 다음 파일 작업시에라도 추가하도록 하겠습니다.

2025-01-01 13:52 UTC, teddylee777 approved these changes
overview 의 모델명 변경과
Table of Contents 링크 동작 안하는 부분 수정해서 commit 하였습니다.
고생 많으셨습니다^^

2025-01-02 06:01 UTC, BAEM1N approved these changes
[Review] - Cache(Caching)

1. Review OS(Windows/Mac/Linux): Mac
2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO): N/A
5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
6. 모든 코드가 동작에 오류 없이 동작하는가? YES 
  - Optional 부분에 대한 실행은 현재 장비에서 확인이 어려우므로, 환경이 세팅되는 대로 실행해 보겠습니다.
7. 기타 의견
  - 수고하셨습니다.

2025-01-02 13:48 UTC, merged