[Team] Existing Tutorial Team 1
LangChain-OpenTutorial/LangChain-OpenTutorial pull request #16
Opened 2024-12-30 01:13 UTC by r14minji

[Title] OpenAI API Key Generation and Testing Guide 
[Version] initial
[Language] ENG
[Packages]

- This guide explains how to get and use an OpenAI API key, including costs and limits.
- To begin, you'll create your API key on OpenAI's platform and set up your development environment.
- After setup, you can test your API key to ensure it works correctly with your applications

2024-12-31 08:35 UTC, jeong-wooseok commented
"[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/langchain-ai/langchain-academy/blob/main/module-4/sub-graph.ipynb) [![Open in LangChain Academy](https://cdn.prod.website-files.com/65b8cd72835ceeacd4449a53/66e9eba12c7b7688aa3dbb5e_LCA-badge-green.svg)](https://academy.langchain.com/courses/take/intro-to-langgraph/lessons/58239937-lesson-2-sub-graphs)\n",
    "\n",
   에서 관련된 깃허브 링크로 변경이 필요합니다. 현재 코랩은 sub-graph.ipynb,  랭체인 아카데미는 58239937-lesson-2-sub-graphs로 연결되네요

2024-12-31 08:37 UTC, jeong-wooseok commented
api키가 유출되지 않는 것을 주의하며 설명하는게 좋은데, 
dotenv 설명하는 곳에도 gitignore파일 만들어서 .env 넣어서 git push에 포함되지 않도록 하는 설명도 넣는게 어떨까 합니다.

2024-12-31 08:54 UTC, jeong-wooseok reviewed
[Review]
1. Review OS(Windows/Mac/Linux): Windows
2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): NO
Table of Contents 링크 클릭시, 연결이 제컴퓨터에서는 안되는 것 같아서 다시 확인 부탁 드립니다.
**4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO):NO
-이미지 파일명
이미지 파일명은 모두 영문 소문자로 작성합니다.
이미지 파일에 공백은 없어야 하며 공백 대신 - 하이픈으로 대체 합니다.

jupyter notebook 파일명 + 이미지 제목 + 필요시 숫자(01, 02, 03, ...)

예시)
10-LangGraph-Self-RAG.ipynb  인 경우

이미지 파일명: 
10-langgraph-self-rag-flow-explanation.png : OK
10-langgraph-self-rag-flow-explanation-01.png: OK**

5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
6. 모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요):
7. 기타 의견:
api키가 유출되지 않는 것을 주의하며 설명하는게 좋은데,
dotenv 설명하는 곳에도 gitignore파일 만들어서 .env 넣어서 git push에 포함되지 않도록 하는 설명도 넣는게 어떨까 합니다.

2025-01-01 13:27 UTC, r14minji commented
@jeong-wooseok  PM님 리뷰 주신 3가지 추가 반영했습니다.
1. 테이블 컨텐츠 이동하도록 수정
2. 이미지 파일 네이밍 규칙에 맞도록 수정
3. gitignore 파일에 env 파일 작성하도록 수정

확인 해주시면 감사하겠습니다 :)

2025-01-02 05:21 UTC, BAEM1N requested changes
[Review] - OpenAI API Key Generation and Testing Guide

Review OS(Windows/Mac/Linux): Mac

Template Rule 가이드를 준수 하였는가(YES/NO): YES

Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES

이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO): NO
  - `./assets/01-basic-guide-01.png` 에서 `02-OpenAIAPIKeyGeneration-01.png` 형태로 변경이 필요해보입니다.
  
import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): NO
  - 기존 튜토리얼의 환경 설정 부분을 `99-TEMPLATE/00-BASE-TEMPLATE-EXAMPLE.ipynb`의 Environment Setup와 같은 형태로 변경이 필요해보입니다.

모든 코드가 동작에 오류 없이 동작하는가? YES

2025-01-02 05:21 UTC, BAEM1N commented on 01-BASIC/02-OpenAIAPIKeyGeneration.ipynb
> +    "![step1](./assets/01-basic-guide-01.png)\n",
`./assets/01-basic-guide-01.png` 에서 `02-OpenAIAPIKeyGeneration-01.png` 형태로 변경이 필요해 보입니다. (다른 이미지 링크와 assets 파일명도 동일하게 수정해 주시면 될 거 같습니다.)

2025-01-02 05:21 UTC, BAEM1N commented on 01-BASIC/02-OpenAIAPIKeyGeneration.ipynb
> +    "!pip install -r https://raw.githubusercontent.com/teddylee777/langchain-kr/main/requirements.txt"
기존 튜토리얼의 환경 설정 부분을 `99-TEMPLATE/00-BASE-TEMPLATE-EXAMPLE.ipynb`의 Environment Setup와 같은 형태로 변경이 필요해보입니다.

2025-01-02 06:43 UTC, r14minji commented on 01-BASIC/02-OpenAIAPIKeyGeneration.ipynb
> +    "![step1](./assets/01-basic-guide-01.png)\n",
파일명 02-OpenAIAPIKeyGeneration-0X.png 으로 수정했습니다

2025-01-02 06:44 UTC, r14minji commented on 01-BASIC/02-OpenAIAPIKeyGeneration.ipynb
> +    "!pip install -r https://raw.githubusercontent.com/teddylee777/langchain-kr/main/requirements.txt"
환경설정 `!pip install langchain-opentutorial` 로 변경했습니다.

2025-01-02 11:05 UTC, cjLee-cmd requested changes
[Review]

1. Review OS(Windows/Mac/Linux): MAC
2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO): YES
5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES(해당없음)
6. 모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): YES
기타 의견:
'Environment/Setting up the .ignore file...' 문장의 끝에 '.'(마침표) 표시 요청.

2025-01-02 11:09 UTC, BAEM1N commented on 01-BASIC/02-OpenAIAPIKeyGeneration.ipynb
> +    "!pip install -r https://raw.githubusercontent.com/teddylee777/langchain-kr/main/requirements.txt"
수고하셨습니다!

2025-01-02 11:09 UTC, BAEM1N commented on 01-BASIC/02-OpenAIAPIKeyGeneration.ipynb
> +    "![step1](./assets/01-basic-guide-01.png)\n",
수고하셨습니다!

2025-01-02 11:11 UTC, BAEM1N approved these changes

2025-01-02 12:37 UTC, r14minji commented
@cjLee-cmd 마침표 추가했습니다

2025-01-02 14:31 UTC, jeong-wooseok approved these changes

2025-01-03 04:44 UTC, merged