[Team] Existing content development teams 3
LangChain-OpenTutorial/LangChain-OpenTutorial pull request #21
Opened 2024-12-30 06:48 UTC by PangPangGod

[Title] Chat Models
[Version] initial
[Language] ENG
[Packages] langsmith, langchain, langchain_openai, langchain_anthropic, langchain_community, langchain_together, langchain_cohere, langchain_upstage,

Introduction to Various Chat Models and Simple Usage Examples

- OpenAI, Anthropic, Perplexity, TogetherAI, Cohere, Upstage API
- (Added) Open LLM Leaderboard
- (Added) Vellum LLM Leaderboard

2025-01-01 12:35 UTC, samdaseuss submitted a review, later dismissed
1. Review OS (Windows/Mac/Linux): MAC  
2. Did it follow the Template Rule guidelines (YES/NO): YES  
3. Did the Table of Contents links work properly (YES/NO): YES  
4. If images are included, do their filenames comply with the guidelines (YES/NO): YES  
5. Does the import statement follow the latest version instead of legacy style (YES/NO): YES  
6. Did all the code run without errors? (If warnings occurred, please comment): YES  
7. Additional Comments: -

2025-01-02 13:52 UTC, sirena1 requested changes
템플릿 통일성을 위하여, Author, Design, Peer Review, This is a part of LangChain Open Tutorial 을 맞춰주시길 바랍니다.
Peer Review 항목이 없습니다.

그 외 코드는 문제 없이 잘 동작합니다!
기존 wikidocs의 내용 외에도 내용이 좀 더 보안되어 좋았습니다. 고생하셨습니다 :)

2025-01-02 20:52 UTC, PangPangGod reviewed
추가 완료했습니다!

2025-01-02 23:19 UTC, sirena1 approved these changes

2025-01-02 23:20 UTC, sirena1 commented
[Review]
1. Review OS(Windows/Mac/Linux): Windows
2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO):YES
5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO):YES
6. 모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): YES
7. 기타 의견: -

2025-01-03 04:44 UTC, merged