[Team] Existing Content Development Team 3
LangChain-OpenTutorial/LangChain-OpenTutorial pull request #22
Opened 2024-12-30 07:06 UTC by Normalist-K

[Title] Video Q&A LLM (Gemini)
[Version] initial
[Language] ENG
[Package] google-generativeai, langchain-google-genai, langchain-core, langsmith

Tutorial for Video Q&A LLM using Gemini
- Using the Gemini API to process and use video content as an input.
- Integerating the Gemini model into a LangChain workflow.

2025-01-01 12:31 UTC, samdaseuss submitted a review, later dismissed
1. Review OS (Windows/Mac/Linux): MAC  
2. Did it follow the Template Rule guidelines (YES/NO): YES  
3. Did the Table of Contents links work properly (YES/NO): YES  
4. If images are included, do their filenames comply with the guidelines (YES/NO): YES  
5. Does the import statement follow the latest version instead of legacy style (YES/NO): YES  
6. Did all the code run without errors? (If warnings occurred, please comment): YES  
7. Additional Comments: -

2025-01-01 14:03 UTC, sooyoung-wind requested changes
`## Building a Chain with the Gemini Model for Video Data (LangChain)`
목차에서 이 부분에 대한 링크가 작동을 안합니다. 내용 확인 부탁드립니다. :)
ps. `(langchain)` 이부분이 빠진듯합니다.

2025-01-02 01:30 UTC, Normalist-K commented
> `## Building a Chain with the Gemini Model for Video Data (LangChain)` 목차에서 이 부분에 대한 링크가 작동을 안합니다. 내용 확인 부탁드립니다. :) ps. `(langchain)` 이부분이 빠진듯합니다.

아 제가 마지막에 변경한 사항이 적용이 안되어있었네요. 다시 수정했습니다!

2025-01-02 02:41 UTC, sooyoung-wind approved these changes

2025-01-02 02:42 UTC, sooyoung-wind commented
> > `## Building a Chain with the Gemini Model for Video Data (LangChain)` 목차에서 이 부분에 대한 링크가 작동을 안합니다. 내용 확인 부탁드립니다. :) ps. `(langchain)` 이부분이 빠진듯합니다.
> 
> 아 제가 마지막에 변경한 사항이 적용이 안되어있었네요. 다시 수정했습니다!

승인했씁니다. 고생하셨습니다. 😄

2025-01-02 06:15 UTC, sooyoung-wind approved these changes

2025-01-02 06:16 UTC, samdaseuss approved these changes
수고하셨습니다 :)

2025-01-02 13:51 UTC, merged