[Team] 기존1팀
LangChain-OpenTutorial/LangChain-OpenTutorial pull request #28
Opened 2024-12-30 18:59 UTC by jeongkpa

[Title] LangSmith Tracking Setup
[Version] initial
[Language] ENG
[Packages] langsmith

-Setting up LangSmith trace configuration
-Implementing project-level tracking and monitoring -Integrating with Jupyter notebooks and Python code -Managing environment variables and API keys
-Using langchain-teddynote for simplified tracking

2024-12-31 07:53 UTC, r14minji requested changes
[Review]
1. Review OS(Windows/Mac/Linux):  Window/ MAc
2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO): NO
- 이미 제출된 파일이라 PASS 하면 될까요?
- 이미지 파일명 가이드는 영문 소문자, 공백 대신 하이픈 - 으로 작성. **언더바 _로 작성된 것을 하이픈 - 으로 대체** 해야합니다. 
- 양식은 **jupyter notebook 파일명 + 이미지 제목 + 필요시 숫자**

5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
6. 모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): YES
7. 기타 의견:
 - 렝체인노트(위키독스) 기준  **LangSmith 의 추적기능**에 관한 설명이 누락되었습니다. 의도하신 바 일까요? 혹시 놓치신 부분이라면 추가 요청드립니다.
 - copy_api_key_image.png 내에 **"테스트 키"** "Test key" 로 영문자로 변경 가능할까요?
 - 렝체인노트(위키독스) 기준 **langchain-teddynote** 하위 컨텐츠가 누락되었었습니다. 이 부분도 혹시 놓친 부분인지, 영어버전에서는 제외하기로 한 부분인지 확인 요청드립니다.

2024-12-31 09:50 UTC, jeongkpa commented
> [Review]
> 
> 1. Review OS(Windows/Mac/Linux):  Window/ MAc
> 2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
> 3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
> 4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO): NO
> 
> * 이미 제출된 파일이라 PASS 하면 될까요?
> * 이미지 파일명 가이드는 영문 소문자, 공백 대신 하이픈 - 으로 작성. **언더바 _로 작성된 것을 하이픈 - 으로 대체** 해야합니다.
> * 양식은 **jupyter notebook 파일명 + 이미지 제목 + 필요시 숫자**
> 
> 5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
> 6. 모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): YES
> 7. 기타 의견:
> 
> * 렝체인노트(위키독스) 기준  **LangSmith 의 추적기능**에 관한 설명이 누락되었습니다. 의도하신 바 일까요? 혹시 놓치신 부분이라면 추가 요청드립니다.
> * copy_api_key_image.png 내에 **"테스트 키"** "Test key" 로 영문자로 변경 가능할까요?
> * 렝체인노트(위키독스) 기준 **langchain-teddynote** 하위 컨텐츠가 누락되었었습니다. 이 부분도 혹시 놓친 부분인지, 영어버전에서는 제외하기로 한 부분인지 확인 요청드립니다.

-> 이미지명 모두 변경 완료
-> 추적기능 추가
-> 랭체인 테디노트는 사용 X

2025-01-01 03:44 UTC, jeong-wooseok approved these changes
[Review]
1. Review OS: Windows
2. Template Rule 가이드를 준수 하였는가: YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?: YES
4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?: YES
5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?: YES
6. 모든 코드가 동작에 오류 없이 동작하는가? : Yes
7. 기타 의견: 
- 확인 완료하였습니다

2025-01-01 13:35 UTC, r14minji commented
[Review] 수정사항 확인

Review OS: Mac
Template Rule 가이드를 준수 하였는가: YES
Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?: YES
이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?: YES
import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?: YES
모든 코드가 동작에 오류 없이 동작하는가? : Yes
기타 의견:
확인 완료하였습니다, approve 진행하겠습니다

2025-01-01 13:35 UTC, r14minji approved these changes

2025-01-02 13:54 UTC, teddylee777 commented
@jeong-wooseok 님 리뷰 감사드립니다.
추후 리뷰시 문제 없다면 approve 로 체크해 주시면 우측 상단에 approve 마킹이 됩니다~ 다음에는 체크 부탁 드려요~

2025-01-02 13:54 UTC, merged