DatetimeOutputParser
LangChain-OpenTutorial/LangChain-OpenTutorial pull request #34
Opened 2024-12-31 09:49 UTC by stsr1284

[Team] Existing content development team 2
[Title] Datetime Output Parser
[Version] initial
[Language] ENG
[Packages] langchain, langchain_core, langchain_openai

Tutorial for Datetime Output Parser
-how to use the Datetime Output Parser

2024-12-31 18:18 UTC, Jae-hoya requested changes
load_dotenv()에서
override=True를 추가해주셔야 할거같습니다!
load_dotenv(override=True) 이렇게요. 아니면 api를 못읽어서 오류가 발생하는거 같아요.

2025-01-01 05:30 UTC, Jae-hoya submitted a review, later dismissed

2025-01-02 09:42 UTC, ranian963 reviewed
Review OS(Windows/Mac/Linux): Mac
Template Rule 가이드를 준수 하였는가(YES/NO): Yes
Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): YES

2025-01-02 09:44 UTC, ranian963 approved these changes
Review OS(Windows/Mac/Linux): Mac
Template Rule 가이드를 준수 하였는가(YES/NO): Yes
Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): YES

2025-01-02 14:55 UTC, musangk approved these changes
[Review]
1. Review OS(Windows/Mac/Linux): Linux
2. Template Rule 가이드를 준수 하였는가(YES/NO): YES
3. Table of Contents 의 링크가 원활하게 동작하는지 확인하였는가?(YES/NO): YES
4. 이미지가 포함되어 있다면, 이미지의 파일명이 가이드를 준수하였는가?(YES/NO): YES
5. import 구문이 예전 legacy 방식이 아닌 최신 버전을 따르는가?(YES/NO): YES
6. 모든 코드가 동작에 오류 없이 동작하는가? (만약, warning 발생시 코멘트에 적어주세요): YES
7. 기타 의견: 모두 잘 동작하는 내용 확인하였습니다. 👍

2025-01-02 15:00 UTC, musangk requested changes
오타 여부 확인하여 수정 부탁드립니다.

2025-01-02 15:00 UTC, musangk commented on 03-OutputParser/06-DatetimeOutputParser.ipynb
> +    "## Implementing the Datetime Output Praser\n",
```suggestion
    "## Implementing the Datetime Output Parser\n",
```
오타 수정 제안드립니다.

2025-01-02 15:00 UTC, musangk commented on 03-OutputParser/06-DatetimeOutputParser.ipynb
> +    "- [Implementing the Datetime Output Praser](#implementing-the-datetime-output-praser)\n",
```suggestion
    "- [Implementing the Datetime Output Parser](#implementing-the-datetime-output-parser)\n",
```
오타 수정 제안드립니다.

2025-01-02 15:07 UTC, stsr1284 commented
> 오타 여부 확인하여 수정 부탁드립니다.

감사합니다. 확인하여 수정 완료하였습니다

2025-01-02 15:37 UTC, musangk approved these changes
수정 내용 확인하였습니다.
빠른 수정 적용 감사합니다.

2025-01-03 05:01 UTC, closed without merging